### ISSUE TITLE
Network timeout on macOS Sierra

### ISSUE THREAD

**Issue by therek** [breiter/vpnc#2]
I'm trying to run vpnc on macOS Sierra (10.12.3). I'm trying to connect to FortiGate v5.2.7. All the VPN setup seems to go well, all the routing entries are applied, but still I have to connectivity to any of the company hosts. I just keep on getting timeouts.

**Comment by jurajpaulo** [comment]
the same problem here, with 10.12.4

**Comment by breiter** [comment]
It's not a Sierra problem. I am using it on 10.12.4 terminating on a Cisco ASA and it works just fine. You may want to (raise the issue with the upstream project)[https://www.unix-ag.uni-kl.de/%7Emassar/vpnc/) vpnc-devel mailing list. It is quite inactive, though. That is to say, it works for me and I have no way of trying to test or fix a FortiGate problem. Sorry. 😢

You might also try [openconnect](http://www.infradead.org/openconnect/index.html) by David Woodhouse, which is in MacPorts and Homebrew. I think that openconnect is a fork of vpnc. David is one of the people who is active on the vpnc-devel mailing list when issues are posted.
